inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - default.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - test/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
